/**
 * Playwright Global Teardown
 * 
 * Performs cleanup tasks that run once after all tests complete,
 * such as cleaning up test data and generating reports.
 */

import { FullConfig } from '@playwright/test';
import { promises as fs } from 'fs';
import path from 'path';

async function globalTeardown(config: FullConfig) {
  console.log('🧹 Starting E2E test global teardown...');
  
  try {
    // Clean up test artifacts if needed
    const testResultsDir = 'test-results';
    
    // Ensure test results directory exists
    try {
      await fs.access(testResultsDir);
    } catch {
      await fs.mkdir(testResultsDir, { recursive: true });
    }
    
    // Generate summary report
    const summaryPath = path.join(testResultsDir, 'e2e-summary.txt');
    const timestamp = new Date().toISOString();
    
    const summary = `
E2E Test Run Summary
===================
Timestamp: ${timestamp}
Configuration: ${config.configFile || 'default'}
Workers: ${config.workers || 1}
Test Directory: ${config.testDir || 'e2e'}

Test Suites:
- Authentication Flow (auth.spec.ts)
- Chat Functionality (chat.spec.ts) 
- Dashboard Functionality (dashboard.spec.ts)
- Integration Workflows (integration.spec.ts)

For detailed results, check:
- HTML Report: test-results/playwright-report/index.html
- JSON Results: test-results/results.json
- JUnit Results: test-results/results.xml

Generated by Virgil E2E Test Suite
    `.trim();
    
    await fs.writeFile(summaryPath, summary);
    console.log(`📊 Test summary written to ${summaryPath}`);
    
    // Clean up temporary files
    const tempDirs = ['test-results/screenshots/temp', 'test-results/videos/temp'];
    
    for (const dir of tempDirs) {
      try {
        await fs.rmdir(dir, { recursive: true });
        console.log(`🗑️  Cleaned up temporary directory: ${dir}`);
      } catch {
        // Directory might not exist, ignore
      }
    }
    
    console.log('✅ Global teardown completed successfully');
    
  } catch (error) {
    console.error('❌ Global teardown failed:', error);
    // Don't throw - teardown failures shouldn't fail the test run
  }
}

export default globalTeardown;